name: Build, Test, and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore PluginUpdater.sln

    - name: Build solution with version
      run: |
        msbuild PluginUpdater.sln /p:Configuration=Release /p:AssemblyVersion=${{ env.VERSION }} /p:FileVersion=${{ env.VERSION }}

    - name: Create GitHub Release and Upload DLL
      uses: softprops/action-gh-release@v1
      with:
        files: release/PluginUpdater.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}