name: Build, Test, and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Update AssemblyInfo version
      run: |
        $version = "${{ env.VERSION }}"
        (Get-Content ./Properties/AssemblyInfo.cs) -replace '(?<=\[assembly: AssemblyVersion\(")[^"]+', $version | Set-Content ./Properties/AssemblyInfo.cs
        (Get-Content ./Properties/AssemblyInfo.cs) -replace '(?<=\[assembly: AssemblyFileVersion\(")[^"]+', $version | Set-Content ./Properties/AssemblyInfo.cs

    - name: Restore NuGet packages
      run: nuget restore PluginUpdater.sln

    - name: Build solution
      run: msbuild PluginUpdater.sln /p:Configuration=Release

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: true