name: Build, Test, and Release

on:
  push:
    tags:
      - '*.*.*'

env:
  version: ${{ github.ref_name }}


jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set version in version.info
      run: |
        $content = Get-Content version.info
        $content = $content -replace '(?<=PluginUpdater:)[0-9\.]+', "${{ env.version }}"
        Set-Content version.info $content

    - name: Commit and push updated version.info
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add version.info
        git commit -m "Set version in version.info to ${{ env.version }}" || echo "No changes to commit"
        git push origin HEAD:main

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore PluginUpdater.sln

    - name: Set version in AssemblyInfo
      shell: pwsh
      run: |
        $asmInfo = Get-ChildItem -Path . -Recurse -Filter AssemblyInfo.cs | Select-Object -First 1
        (Get-Content $asmInfo.FullName) -replace '(?<=AssemblyVersion\(")[^"]+', "${{ env.version }}" | Set-Content $asmInfo.FullName
        (Get-Content $asmInfo.FullName) -replace '(?<=AssemblyFileVersion\(")[^"]+', "${{ env.version }}" | Set-Content $asmInfo.FullName

    - name: Build solution with version
      run: |
        msbuild PluginUpdater.sln /p:Configuration=Release /p:AssemblyVersion=${{ env.version }} /p:FileVersion=${{ env.version }}

    - name: Create GitHub Release and Upload DLL
      uses: softprops/action-gh-release@v1
      with:
        files: release/PluginUpdater.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}